### ISSUE TITLE
"stack smashing detected" in func_web100_snap_from_log

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl#42]
```
*** stack smashing detected ***: /etl_worker terminated
 fatal error: unexpected signal during runtime execution
 [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f01febf7688]
 
 runtime stack:
 runtime.throw(0x9f12d8, 0x2a)
 	/usr/lib/google-golang/src/runtime/panic.go:599 +0x9e
 runtime.sigpanic()
 	/usr/lib/google-golang/src/runtime/signal_unix.go:274 +0x2db 
 goroutine 154 [syscall, locked to thread]:
 runtime.cgocall(0x897350, 0xc42c66b5e8, 0xc400000000)
 	/usr/lib/google-golang/src/runtime/cgocall.go:131 +0xe2 fp=0xc42c66b5b8 sp=0xc42c66b578 pc=0x405282
 github.com/m-lab/etl/web100._Cfunc_web100_snap_from_log(0x7f01f4000b60, 0x7f01f4004380, 0x0)
 	github.com/m-lab/etl/web100/_obj/_cgo_gotypes.go:414 +0x4d fp=0xc42c66b5e8 sp=0xc42c66b5b8 pc=0x82c96d
```

**Comment by stephen-soltesz** [comment]
On it's face, I suspect this is caused by the `tmpbuf` allocated on the stack being overrun by `fscanf`.
https://github.com/m-lab/etl/blob/integration/web100/web100.c#L1613

```
int                                                                            
web100_snap_from_log(web100_snapshot* snap, web100_log *log)                   
{                                                                              
    int c, what;                                                               
    char tmpbuf[MAX_TMP_BUF_SIZE];                                             
    ...                                                                               
```

**Comment by stephen-soltesz** [comment]
Appears to be resolved by:
https://github.com/m-lab/etl/blob/integration/web100/web100.c#L1622
