### ISSUE TITLE
SIGBUS from web100_log_close_read

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl#55]
```
[signal SIGBUS: bus error code=0x80 addr=0x0 pc=0x895f48]

runtime stack:
runtime.throw(0x9ee9cc, 0x2a)
 /usr/lib/google-golang/src/runtime/panic.go:599 +0x9e
runtime.sigpanic()
 /usr/lib/google-golang/src/runtime/signal_unix.go:274 +0x2db

goroutine 1432 [syscall, locked to thread]:
runtime.cgocall(0x895c90, 0xc423ef3378, 0xee82d5ad0)
 /usr/lib/google-golang/src/runtime/cgocall.go:131 +0xe2 fp=0xc423ef3348 sp=0xc423ef3308 pc=0x405282
github.com/m-lab/etl/web100._Cfunc_web100_log_close_read(0x7f03e8100210, 0x7f0300000000)
 github.com/m-lab/etl/web100/_obj/_cgo_gotypes.go:388 +0x49 fp=0xc423ef3378 sp=0xc423ef3348 pc=0x82d679
github.com/m-lab/etl/web100.(*Web100).Close.func2(0x7f03e8100210, 0xc423ef33f8)
 /usr/local/google/home/gfr/go/src/github.com/m-lab/etl/web100/web100.go:195 +0x60 fp=0xc423ef33b0 sp=0xc423ef3378 pc=0x82f970
github.com/m-lab/etl/web100.(*Web100).Close(0xc4240521a0, 0xc4240521a0, 0x0)
 /usr/local/google/home/gfr/go/src/github.com/m-lab/etl/web100/web100.go:195 +0x45 fp=0xc423ef33f8 sp=0xc423ef33b0 pc=0x82eeb5
```

**Comment by stephen-soltesz** [comment]
Believed fixed by a combination of non-global errno, and improved sanity checks throughout web100.c

https://github.com/m-lab/etl/pull/59
https://github.com/m-lab/etl/pull/47
https://github.com/m-lab/etl/pull/58
