### ISSUE TITLE
Traceroute tasks cause panic in universal.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#887]
Panics occur at worker.go:197
  defer tsk.Close()
This should generally succeed, as there is an error handling clause just above that should return if there was a problem creating tsk.  Close() is provided by an etl.TestSource, and in this case should be a storage.GCSSource.

E 2020-05-20T18:57:12.927692768Z 2020/05/20 18:57:12 poller.go:177: all tasks dispatched for gs://archive-measurement-lab/ndt/traceroute/2019/11/14/
 
E 2020-05-20T18:57:13.063582784Z 2020/05/20 18:57:13 worker.go:168: <nil> creating parser for traceroute gs://archive-measurement-lab/ndt/traceroute/2019/11/14/20191114T040334.000730Z-traceroute-mlab1-cpt01-ndt.tgz
 
  undefined
E 2020-05-20T18:57:13.067050167Z panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbecb75]

goroutine 166896 [running]:
github.com/m-lab/etl/worker.ProcessGKETask(0xc000d661c0, 0x6d, 0xc000d661c5, 0x17, 0xc000d661dd, 0x3, 0xc000d661e1, 0xa, 0xc000d661ec, 0xa, ...)
	/go/src/github.com/m-lab/etl/worker/worker.go:197 +0x4e5
main.(*runnable).Run(0xc00261c8c0, 0x10ee580, 0xc008dfa640)
	/go/src/github.com/m-lab/etl/cmd/etl_worker/etl_worker.go:238 +0x2f4
github.com/m-lab/etl/active.(*throttledRunnable).Run(0xc00c66c0a0, 0x0, 0x0)
	/go/src/github.com/m-lab/etl/active/throttle.go:51 +0x67
github.com/m-lab/etl/active.(*GardenerAPI).RunAll.func1(0x0, 0x0)
	/go/src/github.com/m-lab/etl/active/poller.go:114 +0x22a
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00ff648a0, 0xc017ed8b40)
	/go/src/golang.org/x/sync/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/src/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
 
  undefined

**Comment by gfr10598** [comment]
Turns out there is a code path that returns a nil Task and nil error.  Then the task is later dereferenced.  Fixed in PR #889
